language: dart
sudo: false
dart:
  - dev
dart_task:
  - test: --enable-experiment=non-nullable
  - dartfmt
  - dartanalyzer: --fatal-warnings --fatal-infos --enable-experiment=non-nullable .

matrix:
  include:
  - dart: dev
    script: pub run build_runner test -- -p chrome

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
